apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-web
        image: vickylimen1/apache-site:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        resources:
	 requests:
          cpu: "100m"
	  memory: "200Mi"
	 limits:
  	  cpu: "500m"
     	  memory: "500Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
  namespace: apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
	  averageUtilization: 70
