apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-web
  template:
    metadata:
      labels:
        app: apache-web
    spec:
      containers:
      - name: apache-web
        image: vickylimen1/apache-site:<PLACEHOLDER_TAG>
        ports:
        - containerPort: 80
