name: Build & Deploy Apache

on:
  push:
    paths:
      - 'index.html'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & push image
      run: |
        SHA=$(git rev-parse --short HEAD)
        docker build -t vickylimen1/apache-site:$SHA .
        docker push vickylimen1/apache-site:$SHA
        echo "SHA=$SHA" >> $GITHUB_ENV

    - name: Set Git remote to use PAT
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
    
        - run: echo "GH_PAT length: ${{ secrets.GH_PAT && secrets.GH_PAT.length || 0 }}"

    - name: Update deployment.yaml with new tag
      run: |
        sed -i "s|image: vickylimen1/apache-site:.*|image: vickylimen1/apache-site:${{ env.SHA }}|" k3s/deployment.yaml
      
        - run: echo "Remote URL: https://x-access-token:***@github.com/${{ github.repository }}"

    - name: Commit & push updated deployment.yaml
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add k3s/deployment.yaml
        git commit -m "Update image to ${{ env.SHA }}" || echo "No changes to commit"
        git push
